import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 10,
  },
  QRContainer: {
    flex: 1,
    paddingHorizontal: 20,
    margin: 20,
    marginTop: 80,
  },
  settingsContainer: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 20,
    paddingHorizontal: 20,
  },
  profileContainer: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 40,
    padding: 20,
  },
  header: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingTop: 30,
    borderBottomColor: "#00CDBC",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  logo: {
    width: 80,
    height: 80,
  },
  categoryButton: {
    backgroundColor: "#ff9900",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginRight: 10,
  },
  categoryButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 30,
  },
  modalContent: {
    height:"100%",
    width:'100%'
  },
  categoryItem: {
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  categoryItemText: {
    fontSize: 16,
    color: "#333",
  },
  productsContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  badge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "transparent",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#fff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    zIndex: 2,
  },
  badgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "Futura",
  },
  userInfo: {
    marginBottom: 20,
    textAlign: "center",
  },

  settingsIcon: {
    marginBottom: 20,
  },
  settingsTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
  },
 
  settingsOptionText: {
    marginLeft: 10,
    fontSize: 18,
    color: "#333",
    fontFamily: "Futura",
  },
  productInterests: {
    marginTop: 20,
  },
  productInterestsTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 10,
    fontFamily: "Futura",
    color: "#00CDBC",
  },
  interestsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  interestItem: {
    backgroundColor: "#2D3250",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginHorizontal: 5,
    marginVertical: 5,
  },
  selectedInterest: {
    backgroundColor: "#00CDBC",
  },
  interestText: {
    fontSize: 12,
    color: "white",
    fontFamily: "Futura",
  },
  toggleButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    alignItems: "flex-end",
    marginTop: 10,
  },
  mockScannerContainer: {
    flex: 1,
    width: "100%",
  },
  mockScannerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
  },
  scannedItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    marginBottom: 10,
    borderRadius: 10,
    elevation: 2,
  },
  scannedItemType: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  scannedItemData: {
    fontSize: 16,
    color: "#666",
  },
  scanButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#00CDBC",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 20,
  },
  scanButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginLeft: 10,
  },
  toggleButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#00CDBC",
    borderRadius: 50,
    padding: 10,
    elevation: 3,
  },
  square: {
    backgroundColor: "#000",
    height: 100,
    width: 100,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  squareContainer: {
    marginBottom: 280,
  },
  squareText: {
    fontFamily: "Futura",
    marginTop: 20,
    fontWeight: "700",
    textAlign: "center",
    color: "white",
    fontSize: 10,
    letterSpacing: 1,
  },
  categoryContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    marginBottom: 5,
    justifyContent: "space-between",
  },
  categoryButton: {
    backgroundColor: "#000",
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  categoryButtonText: {
    color: "#fff",
    fontWeight: "400",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.1)",
  },
  modalContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#eee",
    borderTopLeftRadius: 30,
    borderTopRightRadius:30,
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom:50,
    backgroundColor: "#fff",
  },
  modalContent: {
    paddingTop: 20,
    paddingBottom: 10,
    backgroundColor: "#fff",
  },
  categoryItem: {
    paddingVertical: 15,
    borderBottomWidth: 0.2,
    borderBottomColor: "#ccc",
  },
  categoryItemText: {
    fontSize: 16,
    color: "#000",
    fontFamily: "Helvetica",
  },
  productsContainer: {
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  productContainer: {
    flexDirection: "row",
    backgroundColor: "#fff",
    margin: 10,
    padding: 30,
    borderRadius: 5,
    marginBottom: 5,
  },
  productImage: {
    width: 100,
    height: 120,
    resizeMode: "cover",
  },
  productInfo: {
    flex: 1,
    padding: 10,
  },
  productName: {
    fontSize: 13,
    fontWeight: "500",
    marginBottom: 5,
    fontFamily: "Helvetica Neue",
    width: 120,
    marginBottom: 5,
  },
  productPrice: {
    fontSize: 12,
    color: "#555",
    fontWeight: "400",
    fontFamily: "Helvetica Neue",
  },
  productID: {
    fontSize: 10,
    color: "#000",
    marginBottom: 5,
    fontWeight: "bold",
    marginBottom: 5,
  },
  badge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "transparent",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#fff",
    paddingHorizontal: 8,
    paddingVertical: 4,
    zIndex: 2,
  },
  badgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "Futura",
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 60,
    marginBottom: 20,
    alignSelf: "center",
    marginTop:10,
  },
  userInfo: {
    marginBottom: 20,
  },
  username: {
    fontSize: 18,
    fontWeight: "500",
    marginBottom: 5,
    textAlign: "center",
    fontFamily: "Arial",
  },
  email: {
    fontSize: 12,
    color: "#00CDBC",
    textAlign: "center",
  },
  bio: {
    textAlign: "center",
  },
  settingsButton: {
    paddingVertical: 5,
    alignSelf: "center",
    marginBottom: 10,
    marginTop: 10,
    borderWidth:1,
    borderColor:'silver',
    width:200,
  },
  settingsButtonText: {
    fontSize: 12,
    color: "#000",
    textAlign:'center',
    fontWeight:'600'
  },
  settingsIcon: {
    marginBottom: 20,
  },
  settingsTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
  },
  settingsOption: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f9f9f9",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginVertical: 5,
  },
  settingsOptionText: {
    marginLeft: 10,
    fontSize: 18,
    color: "#333",
  },
  paginationContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
    marginTop: 5,
  },
  paginationButton: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 5,
    marginHorizontal: 5,
  },
  paginationButtonText: {
    color: "#fff",
    fontSize: 16,
  },
  pageNumberText: {
    fontSize: 12,
    fontWeight: "bold",
    fontFamily: "Futura",
    marginHorizontal: 10,
  },
  disabledButton: {
    opacity: 0.4,
  },
  loadingContainer: {
    alignSelf: "center",
    marginTop: 400,
  },
  searchBarContainer: {
    width: "100%",
    alignSelf: "center",
    padding: 5,
  },
  columnButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  columnButton: {
    backgroundColor: "#f0f0f0",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  selectedColumnButton: {
    backgroundColor: "#007bff",
    borderColor: "#007bff",
  },
  columnButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  selectedColumnButtonText: {
    color: "#fff",
  },
  modalCentered: {
    flex: 1,
    position: "absolute",
    left: 30,
    top: 150,
    alignItems: "center",
  },
  optionsMenu: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    width: width * 0.8,
    maxHeight: height * 0.6,
    elevation: 5,
  },
  option: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  optionText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  closeButton: {
    position: "absolute",
    top: 20,
    right: 20,
    backgroundColor: "transparent",
  },
  closeButtonText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#666",
    zIndex:100
  },
  favoriteItems: {
    marginTop: 20,
    paddingHorizontal: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  favoriteItem: {
    marginRight: 10,
  },
  favoriteItemImage: {
    width: 50,
    height: 50,
    resizeMode: "contain",
    alignSelf: "center",
    borderRadius: 10,
  },
  favoriteItemText: {
    marginTop: 5,
  },
  socialMediaLinks: {
    flexDirection: "row",
    justifyContent: "space-around",
    verticalAlign: "middle",
    padding: 15,
    marginTop: 30,
    marginBottom: 5,
    backgroundColor: "whitesmoke",
    borderRadius: 10,
  },
  settingLinks: {
    flexDirection: "row",
    justifyContent: "space-around",
    verticalAlign: "middle",
    padding: 15,
    marginTop: 5,
    marginBottom: 5,
    borderRadius: 10,
  },
  socialLink: {
    flexDirection: "row",
    alignItems: "center",
  },
  settingLink:{
    borderLeftWidth:0.5,
    paddingLeft:20,
    borderLeftColor:'silver'
  },
  socialLinkText: {
    fontSize: 16,
  },
  greetingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    backgroundColor: "#00CDBC",
    borderRadius: 10,
    marginBottom: 20,
  },
  greeting: {
    color: "#000",
    fontSize: 20,
    fontWeight: "400",
    margin: 10,
    marginLeft: 20,
    fontFamily: "Helvetica Neue",
  },
  heading: {
    fontSize: 20,
    marginLeft: 10,
    fontFamily: "Helvetica Neue",
  },
  heading2: {
    fontSize: 20,
    marginLeft: 10,
    color: "#777",
    fontFamily: "Helvetica Neue",
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '100%', 
    height: '100%', 
    backgroundColor: '#fff', 
    borderRadius: 10,
  },
  closeButtonText: {
    alignSelf: 'flex-end',
    marginTop: 10,
    color: 'blue',
  },
});

export default styles;
